language: generic
sudo: required by
services:
  - docker

before_install:
  - docker build -t jeffhogg86/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jeffhogg86/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-west-1'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-west-1-822123536206'
  bucket_path: 'docker-react'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
